apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/ports/0/nodePort
        - /spec/ports/1/nodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    # Source 1: Helm chart from public OCI registry
    - repoURL: ghcr.io/nginx/charts
      chart: nginx-ingress
      targetRevision: 2.5.0
      helm:
        valueFiles:
          - $values/nginx-ingress/values.yaml
      name: chart

    # Source 2: Values file from Git
    - repoURL: https://github.com/idan-codefresh/finpay-deploy.git
      targetRevision: main
      ref: values
      name: values
